services:
  - type: worker
    name: ft-scraper
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_SECURE
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: EMAIL_SUBJECT
        sync: false 